/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.Connect;
import Process.EMPLOYEE;
import Process.MD5;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableStringConverter;
import other.VNCharacterUtils;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Acer
 */
public final class FrmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmployee
     */
    EMPLOYEE emp = new EMPLOYEE();
    MD5 md = new MD5();
    Connect con = new Connect();
    private Component frame;

    public FrmEmployee() {
        initComponents();
        tableContent();
        this.setExtendedState(FrmMenu.MAXIMIZED_BOTH);
        try {
            ShowData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void tableContent() {
        JTableHeader tableheader = tblDanhSachNhanVien.getTableHeader();
        tableheader.setFont(new Font("Tahoma", Font.BOLD, 16));

        DefaultTableCellRenderer textRenderer = new DefaultTableCellRenderer();
        textRenderer.setHorizontalAlignment(JLabel.LEFT);

        for (int i = 0; i < tblDanhSachNhanVien.getColumnCount(); i++) {
            tblDanhSachNhanVien.getColumnModel().getColumn(i).setCellRenderer(textRenderer);
        }
    }

    public void ShowData() throws SQLException {
        ResultSet result = emp.getAllEMPLOYEE();
        DefaultTableModel tableModel = (DefaultTableModel) tblDanhSachNhanVien.getModel();
        tableModel.setRowCount(0); //clear table
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[7];
                rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 
                rows[1] = result.getString(2); // lấy dữ liệu tai cột số 2 
                rows[2] = result.getString(3); // lấy dữ liệu tai cột số 3
                rows[3] = result.getString(5); // lấy dữ liệu tai cột số 5
                rows[4] = result.getString(6); // lấy dữ liệu tai cột số 6
                rows[5] = result.getString(7); // lấy dữ liệu tai cột số 6               
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel
            }
        } catch (SQLException e) {
        }
    }

    //Kiem tra du lieu
    public boolean CheckData(String fullname, String username, String password, String phone, String role, String image) {
        if (phone.length() != 10) {
            JOptionPane.showMessageDialog(frame, "Vui lòng nhập đúng SĐT!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (fullname.isEmpty() || username.isEmpty() || password.isEmpty() || phone.isEmpty() || role.isEmpty() || image == null || image == "") {
            JOptionPane.showMessageDialog(frame, "Vui lòng nhập đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorth = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblwelcome = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachNhanVien = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        pnlEast = new javax.swing.JPanel();
        lblTenNhanVien = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblMoTa1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblMoTa2 = new javax.swing.JLabel();
        lblMoTa3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        CmbRole = new javax.swing.JComboBox<>();
        txtTenTaiKhoan = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1535, 872));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANG QUẢN LÝ NHÂN VIÊN");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblwelcome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNorthLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(lblwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(426, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblwelcome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jScrollPane2.setAlignmentX(2.0F);
        jScrollPane2.setAlignmentY(2.0F);

        tblDanhSachNhanVien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblDanhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Tên tài khoản", "Số điện thoại", "Chức vụ", "Hình ảnh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachNhanVien.setShowGrid(true);
        tblDanhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachNhanVien);
        if (tblDanhSachNhanVien.getColumnModel().getColumnCount() > 0) {
            tblDanhSachNhanVien.getColumnModel().getColumn(5).setResizable(false);
            tblDanhSachNhanVien.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                    .addComponent(txtTimKiem))
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlEast.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên:");

        txtTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenNhanVien.setPreferredSize(new java.awt.Dimension(7, 0));
        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMatKhau.setText("Mật khẩu:");

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhone.setPreferredSize(new java.awt.Dimension(7, 0));

        lblMoTa1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMoTa1.setText("Chức vụ:");

        btnSua.setBackground(new java.awt.Color(102, 255, 204));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.setBorderPainted(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 255, 153));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setBorderPainted(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 102));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorderPainted(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblMoTa2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMoTa2.setText("Số điện thoại:");

        lblMoTa3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMoTa3.setText("Tên tài khoản:");

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMatKhau.setPreferredSize(new java.awt.Dimension(7, 0));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        CmbRole.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên", "Cộng tác viên" }));
        CmbRole.setBorder(null);
        CmbRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbRoleMouseClicked(evt);
            }
        });
        CmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbRoleActionPerformed(evt);
            }
        });

        txtTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenTaiKhoan.setPreferredSize(new java.awt.Dimension(7, 0));

        lblImage.setBackground(new java.awt.Color(0, 51, 102));
        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("Chọn ảnh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEastLayout = new javax.swing.GroupLayout(pnlEast);
        pnlEast.setLayout(pnlEastLayout);
        pnlEastLayout.setHorizontalGroup(
            pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEastLayout.createSequentialGroup()
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEastLayout.createSequentialGroup()
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlEastLayout.createSequentialGroup()
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEastLayout.createSequentialGroup()
                                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoTa2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEastLayout.createSequentialGroup()
                                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoTa3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEastLayout.setVerticalGroup(
            pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEastLayout.createSequentialGroup()
                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEastLayout.createSequentialGroup()
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lblMoTa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lblMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lblMoTa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(673, 673, 673))
        );

        getContentPane().add(pnlEast, java.awt.BorderLayout.EAST);
        pnlEast.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        String Fullname = this.txtTenNhanVien.getText();
        String Username = this.txtTenTaiKhoan.getText();
        String Password = String.valueOf(MD5.encrypt(txtMatKhau.getText()));
        String Phone = this.txtPhone.getText();
        String Role = String.valueOf(CmbRole.getSelectedItem());
        String image = lblImage.getText();
        if (!CheckData(Fullname, Username, Password, Phone, Role, image)) {
            return;
        }
        try {
            emp.insertEmployee(Fullname, Username, Password, Phone, Role, image);
            btnLamMoiActionPerformed(evt);
            ShowData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int[] index = tblDanhSachNhanVien.getSelectedRows();

        if (index.length == 0) {
            JOptionPane.showMessageDialog(frame, "Vui lòng chọn nhân viên", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (index.length >= 1) {
            for (int i = 0; i < index.length; i++) {
                Object EmployeeID = tblDanhSachNhanVien.getValueAt(index[i], 0);
                Object productName = tblDanhSachNhanVien.getValueAt(index[i], 1);
                int dialog = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhân viên \"" + productName + "\" ra khỏi danh sách ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (dialog == JOptionPane.YES_OPTION) {
                    try {
                        emp.deleteEmployee(EmployeeID);
                        btnLamMoiActionPerformed(evt);
                        ShowData();
                        JOptionPane.showMessageDialog(frame, "Đã xóa nhân viên \"" + productName + "\" ra khỏi danh sách", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        this.txtTenNhanVien.setText(null);
        this.txtTenTaiKhoan.setText(null);
        this.txtPhone.setText(null);
        this.txtMatKhau.setText(null);
        lblImage.setText("");
        lblImage.setIcon(null);
        btnThem.setEnabled(true);
        ImageIcon ImgIcon = new ImageIcon(getClass().getResource("/Image/user.png"));
        Image newImage = ImgIcon.getImage().getScaledInstance(153, 190, Image.SCALE_SMOOTH);
        ImageIcon Icon = new ImageIcon(newImage);
        lblImage.setIcon(Icon);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int index = tblDanhSachNhanVien.getSelectedRow();
        int rowcount = tblDanhSachNhanVien.getSelectedRowCount();
        if (rowcount == 0) {
            JOptionPane.showMessageDialog(frame, "Vui lòng chọn nhân viên", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (rowcount > 1) {
            JOptionPane.showMessageDialog(frame, "Vui lòng chỉ chọn một nhân viên", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Object EmployeeID = tblDanhSachNhanVien.getValueAt(index, 0);
                String Fullname = this.txtTenNhanVien.getText();
                String Username = this.txtTenTaiKhoan.getText();
                String Password = String.valueOf(MD5.encrypt(txtMatKhau.getText()));
                String Phone = this.txtPhone.getText();
                String Role = String.valueOf(CmbRole.getSelectedItem());
                String image = this.lblImage.getText();
                if (!CheckData(Fullname, Username, Password, Phone, Role, image)) {
                    return;
                }
                if (Integer.parseInt(EmployeeID.toString()) == 1) {
                    emp.editEmployee(EmployeeID, Fullname, Username, Phone, "Admin", image);
                } else {
                    emp.editEmployee(EmployeeID, Fullname, Username, Phone, Role, image);
                }
                btnLamMoiActionPerformed(evt);
                ShowData();
                JOptionPane.showMessageDialog(frame, "Đã cập nhật thông tin cho nhân viên \"" + Fullname + "\"", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(FrmEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblDanhSachNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNhanVienMouseClicked

        int index = this.tblDanhSachNhanVien.getSelectedRow();
        String Fullname = this.tblDanhSachNhanVien.getValueAt(index, 1).toString();
        String Username = this.tblDanhSachNhanVien.getValueAt(index, 2).toString();
        String Phone = this.tblDanhSachNhanVien.getValueAt(index, 3).toString();
        CmbRole.addItem(tblDanhSachNhanVien.getValueAt(index, 4).toString());
        CmbRole.removeItemAt(3);

        if (this.tblDanhSachNhanVien.getValueAt(index, 5) == null) {
            ImageIcon ImgIcon = new ImageIcon(getClass().getResource("/Image/user.png"));
            Image newImage = ImgIcon.getImage().getScaledInstance(153, 190, Image.SCALE_SMOOTH);
            ImageIcon Icon = new ImageIcon(newImage);
            lblImage.setIcon(Icon);

        } else {
            String image = this.tblDanhSachNhanVien.getValueAt(index, 5).toString();
            lblImage.setText(image);
            ImageIcon ImgIcon = new ImageIcon(getClass().getResource("/Image/" + image));
            Image newImage = ImgIcon.getImage().getScaledInstance(153, 190, Image.SCALE_SMOOTH);
            ImageIcon Icon = new ImageIcon(newImage);
            lblImage.setIcon(Icon);
        }
        this.txtTenNhanVien.setText(Fullname);
        this.txtTenTaiKhoan.setText(Username);
        this.txtPhone.setText(Phone);
        btnThem.setEnabled(false);

    }//GEN-LAST:event_tblDanhSachNhanVienMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String keyword = txtTimKiem.getText();
        DefaultTableModel tableModel = (DefaultTableModel) tblDanhSachNhanVien.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(tableModel);
        tblDanhSachNhanVien.setRowSorter(tr);

        tr.setStringConverter(new TableStringConverter() {
            @Override
            public String toString(TableModel model, int row, int column) {
                return VNCharacterUtils.removeAccent(model.getValueAt(row, column).toString()).toLowerCase();
            }
        });

        tr.setRowFilter(RowFilter.regexFilter(keyword));
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        txtTimKiem.setText("Tìm kiếm");
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void CmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbRoleActionPerformed

    private void CmbRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbRoleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbRoleMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFileter = new FileNameExtensionFilter("hình ảnh", "jpg", "png");
        fileChooser.setFileFilter(imageFileter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "chọn file");
        if (x == JFileChooser.APPROVE_OPTION) {
            try {
                File choosed_file = fileChooser.getSelectedFile();
                String fileName = "";
                if (choosed_file.toString().contains(".png")) {
                    fileName = txtTenTaiKhoan.getText() + ".png";
                } else {
                    fileName = txtTenTaiKhoan.getText() + ".jpg";
                }
                String file_destination = getClass().getResource("/Image/").getFile() + fileName;
                BufferedImage bi = ImageIO.read(choosed_file);
                ImageIO.write(bi, "jpg", new File(file_destination));

                ImageIcon image = new ImageIcon(file_destination);
                Image newImage = image.getImage().getScaledInstance(153, 190, Image.SCALE_SMOOTH);
                ImageIcon Icon = new ImageIcon(newImage);
                lblImage.setText(fileName);
                lblImage.setIcon(Icon);

            } catch (IOException ex) {
                Logger.getLogger(FrmEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmMain FrmMain = new FrmMain();
        this.setVisible(false);
        FrmMain.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbRole;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblMoTa1;
    private javax.swing.JLabel lblMoTa2;
    private javax.swing.JLabel lblMoTa3;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlEast;
    private javax.swing.JPanel pnlNorth;
    public javax.swing.JTable tblDanhSachNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

}
