/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Acer
 */
public class FrmMain extends javax.swing.JFrame {
//    /**
//     * Creates new form Frm_mainmenu
//     */

    public FrmMain() {
        initComponents();
        String Role = DTO.CurrentUser.user.getRole();
        lbl_username.setText("Xin chào, " + DTO.CurrentUser.user.getFullname());
        lbl_role.setText(Role);
        //getavatar
        String f = DTO.CurrentUser.user.getImage();
        String file = f.toString();
        lblavatar.setText(DTO.CurrentUser.user.getImage());
        String fileName = file.substring(file.lastIndexOf('\\') + 1);
        lblavatar.setText(fileName);
        ImageIcon image = new ImageIcon(getClass().getResource("/Image/").getFile() + f);
        Image newImage = image.getImage().getScaledInstance(lblavatar.getWidth(), lblavatar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon Icon = new ImageIcon(newImage);
        lblavatar.setIcon(Icon);
        checkRole(DTO.CurrentUser.user.getRole());
    }

    public void checkRole(String Role) {
        if (Role.equals("Nhân viên") || Role.equals("Cộng tác viên")) {
            Disabled();
        }
    }

    private void Disabled() {
        btn_customer.setEnabled(false);
        btn_discount.setEnabled(false);
        btn_employee.setEnabled(false);
        btn_product.setEnabled(false);
        btn_revenue.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_North = new javax.swing.JPanel();
        lblavatar = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        pnl_Center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_product = new javax.swing.JButton();
        btn_order = new javax.swing.JButton();
        btn_revenue = new javax.swing.JButton();
        btn_discount = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_customer = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        btn_information = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý quán cà phê");
        setSize(new java.awt.Dimension(1280, 720));

        pnl_North.setBackground(new java.awt.Color(103, 163, 231));

        lblavatar.setBackground(new java.awt.Color(255, 0, 0));
        lblavatar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblavatar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Vai trò   : ");

        lbl_role.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_role.setForeground(new java.awt.Color(255, 255, 255));
        lbl_role.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_role.setText("Giám đốc");

        lbl_logo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/glass-48x48-129684.png"))); // NOI18N
        lbl_logo.setText("TDV COFFEE");

        javax.swing.GroupLayout pnl_NorthLayout = new javax.swing.GroupLayout(pnl_North);
        pnl_North.setLayout(pnl_NorthLayout);
        pnl_NorthLayout.setHorizontalGroup(
            pnl_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NorthLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 565, Short.MAX_VALUE)
                .addComponent(lblavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_NorthLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(lbl_role, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        pnl_NorthLayout.setVerticalGroup(
            pnl_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_NorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblavatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_NorthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_role, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(pnl_North, java.awt.BorderLayout.NORTH);

        pnl_Center.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));

        btn_product.setBackground(new java.awt.Color(255, 255, 204));
        btn_product.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kettle-64x64-129686.png"))); // NOI18N
        btn_product.setText("Đồ uống");
        btn_product.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_product.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productActionPerformed(evt);
            }
        });

        btn_order.setBackground(new java.awt.Color(255, 255, 204));
        btn_order.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paper-64x64-129688.png"))); // NOI18N
        btn_order.setText("Bán hàng");
        btn_order.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_order.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_order.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_orderActionPerformed(evt);
            }
        });

        btn_revenue.setBackground(new java.awt.Color(255, 255, 204));
        btn_revenue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_revenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/revenue.png"))); // NOI18N
        btn_revenue.setText("Doanh thu");
        btn_revenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_revenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_revenue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revenueActionPerformed(evt);
            }
        });

        btn_discount.setBackground(new java.awt.Color(255, 255, 204));
        btn_discount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_discount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/discount.png"))); // NOI18N
        btn_discount.setText("Khuyến mãi");
        btn_discount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_discount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_discount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_discountActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(255, 255, 204));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btn_exit.setText("Thoát");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 255, 204));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_customer.setBackground(new java.awt.Color(255, 255, 204));
        btn_customer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        btn_customer.setText("Khách hàng");
        btn_customer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_customer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerActionPerformed(evt);
            }
        });

        btn_employee.setBackground(new java.awt.Color(255, 255, 204));
        btn_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.png"))); // NOI18N
        btn_employee.setText("Nhân viên");
        btn_employee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_employee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_employee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        btn_information.setBackground(new java.awt.Color(255, 255, 204));
        btn_information.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/infor.png"))); // NOI18N
        btn_information.setText("Thông tin");
        btn_information.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        btn_information.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_information.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_order, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btn_product, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_information, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_order, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_product, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_discount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_information, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_Center.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_Center, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revenueActionPerformed
        FrmRevenueManagement frm = new FrmRevenueManagement();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_revenueActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        FrmEmployee frm = new FrmEmployee();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        DTO.CurrentUser.user = null;
        FrmLogin Frm = new FrmLogin();
        this.dispose();
        Frm.setVisible(true);

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informationActionPerformed
        // TODO add your handling code here:
        FrmAbout FrmInf = new FrmAbout();
        FrmInf.setVisible(true);
    }//GEN-LAST:event_btn_informationActionPerformed

    private void btn_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_orderActionPerformed
        FrmOrder frm = new FrmOrder();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_orderActionPerformed

    private void btn_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerActionPerformed
        FrmCustomer frm = new FrmCustomer();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_customerActionPerformed

    private void btn_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_discountActionPerformed
        FrmDiscount frm = new FrmDiscount();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_discountActionPerformed

    private void btn_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productActionPerformed
        FrmMenu frm = new FrmMenu();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_customer;
    private javax.swing.JButton btn_discount;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_information;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_order;
    private javax.swing.JButton btn_product;
    private javax.swing.JButton btn_revenue;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lblavatar;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_North;
    // End of variables declaration//GEN-END:variables
}
